version: '3.2'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ""
      HOSTNAME: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - '5672:5672'
      - '15672:15672'
    labels:
      NAME: rabbitmq
    volumes:
      - '~/docker/${PROJECT_NAME}/var/lib/rabbitmq:/var/lib/rabbitmq'
    networks:
      - indian_net
  mariadb:
    image: 'mariadb:10.4.12'
    restart: always
    ports:
      - '33060:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_HOST=%'
      - 'TZ="Asia/Seoul"'
      - 'MYSQL_DATABASE=game'
    volumes:
      - './mysql/conf.d:/etc/mysql/conf.d'
      - './mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:rw'
      - '~/docker/${PROJECT_NAME}/var/lib/mysql:/var/lib/mysql'
    networks:
      - indian_net
  mongodb:
    image: 'mongo:4.2.3'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - '~/docker/${PROJECT_NAME}/data/db:/data/db'
  spring-boot-game:
    build: ./game
    ports:
      - '9091:9090'
    depends_on:
      - mariadb
    networks:
      - indian_net
  spring-boot-logging:
    build: ./logging
    ports:
      - '9092:9090'
    depends_on:
      - mariadb
      - rabbitmq
    networks:
      - indian_net
  spring-boot-security:
    build: ./security
    ports:
      - '9093:9090'
    depends_on:
      - mariadb
    networks:
      - indian_net
networks:
  indian_net:
    driver: bridge

