version: '3.2'
services:
  rabbitmq:
    image: 'rabbitmq:management'
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ""
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - '5672:5672'
      - '15672:15672'
    labels:
      NAME: rabbmitmq
  mariadb:
    image: 'mariadb:10.4.12'
    restart: always
    ports:
      - '33060:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}'
      - 'TZ="Asia/Seoul"'
    volumes:
      - '~/docker/${PROJECT_NAME}/var/lib/mysql:/var/lib/mysql'
      - '~/docker/${PROJECT_NAME}/var/log/maria:/var/log/maria'
  mongodb:
    image: 'mongo:4.2.3'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - '~/docker/${PROJECT_NAME}/data/db:/data/db'
  spring-boot-game:
    build: ./game
    ports:
      - '9091:9090'
    depends_on:
      - mariadb
    networks:
      - indian_net
  spring-boot-logging:
    build: ./logging
    ports:
      - '9092:9090'
    depends_on:
      - mariadb
    networks:
      - indian_net
  spring-boot-security:
    build: ./logging
    ports:
      - '9093:9090'
    depends_on:
      - mariadb
    networks:
      - indian_net
networks:
  indian_net:
    driver: bridge

